# global settings
title: "PLATEAU Workshop"
description: "Bringing together Programming Languages and Human-Computer Interaction"
url: "https://schasins.com/plateau/" # the base hostname & protocol for your site, e.g. http://example.com
year: 2026
# colocated_url: "https://2020.splashcon.org/"
# colocated_logo: "./assets/images/splash2020.png"
# colocated_title: "SPLASH2020"
logo_height: "30px"
location: "@ Carnegie Mellon University, Pittsburgh, PA USA"
#sublocation: "TBD"
workshop_date: "Early March, exact dates TBA!"
submission_date: "Wednesday, December 17th, 2025"
#notification_date: "Wednesday, December 13th, 2023"
#backup_submission_date: ""
#submission_site: "https://easychair.org/conferences/?conf=plateau2026"
#registration_site: "https://forms.gle/U6zCxWZ2dvUkY7tX6"
mailing_list_link: "https://groups.google.com/g/plateau-announcements"
#proceedings_site: "TBD"
# room_number_or_description:

organizers:
  - name: Sarah E. Chasins
    affiliation: University of California, Berkeley
  - name: Joshua Sunshine
    affiliation: Carnegie Mellon University

student_organizers:
  - name: Justin Lubin
    affiliation: University of California - Berkeley
  - name: Yiliang "Leo" Liang
    affiliation: Carnegie Mellon University
  - name: Eric Rawn
    affiliation: University of California - Berkeley

mentors:
  - name: Titus Barik
    affiliation: Apple
  - name: Alan Blackwell
    affiliation: University of Cambridge
  - name: Harry Goldstein
    affiliation: University of Buffalo
  - name: Shriram Krishnamurthi
    affiliation: Brown University
  - name: Toby Li
    affiliation: Notre Dame
  - name: Steve Oney
    affiliation: University of Michigan
  - name: Nadia Polikarpova
    affiliation: UC San Diego
  - name: Mark Santolucito
    affiliation: Barnard

# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from

navbar_links:
  - title: "Home"
    url: "/"
    newtab: false
  # - title: "Registration"
  #   url: "/registration"
  #   newtab: false
  # - title: "Program"
  #   url: "/program"
  #   newtab: false
  - title: "Prior Year Sites"
    url: "/prior-year-sites"
    newtab: false
